Repository gchatzopoulosCC/battlesnake, pull requests merged in 2025-04, with the labels that each got.

#9 Refactor Base Structure
  index.js
  src/common/move.js
  src/core/game.js
  src/core/snake.js
Labels: refactor

#16 Add a pull request template in .github/
  .github/pull_request_template.md
Labels: enhancement, requirement

#15 Feature/avoid collision with itself
  src/common/move.js
  src/core/snake.js
Labels: requirement

#18 Move functions' optimization
  src/common/move.js
Labels: enhancement, refactor

#28 Patch/update develop from main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  package-lock.json
  package.json
Labels: dependencies

#31 Patch/user story template
  .github/ISSUE_TEMPLATE/user_story.md
  newfile.js
  package-lock.json
  package.json
Labels: enhancement

#41 Feature/eslint
  eslint.config.js
  package-lock.json
  package.json
Labels: enhancement, requirement, javascript

#45 Feature/eslint
  eslint.config.js
Labels: enhancement

#44 feat: Create and configure .editorconfig
  .editorconfig
Labels: enhancement, requirement

#46 Keep develop up to date with main
  package-lock.json
Labels: bug

#48 fix: generate a new package-lock.json
  package-lock.json
Labels: bug, dependencies

#52 feat: Add the required eslint plugins
  eslint.config.js
  package-lock.json
  package.json
Labels: enhancement, requirement

#53 fix: change the dependabot npm schedule to weekly, monday 5:00 and ch…
  .github/dependabot.yml
Labels: enhancement

#55 Feature/prettier
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/blank.yml
  .prettierignore
  .prettierrc.json
  README.md
  index.js
  package-lock.json
  package.json
  server.js
  src/common/move.js
  src/core/game.js
  src/core/snake.js
Labels: enhancement, requirement

#57 Make a file for each move function
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/blank.yml
  .prettierignore
  .prettierrc.json
  README.md
  eslint.config.js
  index.js
  package-lock.json
  package.json
  server.js
  src/common/move.js
  src/core/game.js
  src/core/snake.js
  src/moves/avoidGoingBackwards.js
  src/moves/avoidOthers.js
  src/moves/avoidSelf.js
  src/moves/avoidWalls.js
Labels: refactor

#59 Develop
  CHANGELOG.md
Labels: enhancement, requirement, refactor, javascript
